OBJECTS:= kernel/arch/$(ARCH)/start.o $(OBJECTS) kernel/arch/$(ARCH)/io.o \
	kernel/arch/$(ARCH)/descriptor_tables.o kernel/arch/$(ARCH)/descriptor_tables_s.o \
	kernel/arch/$(ARCH)/interrupt.o kernel/arch/$(ARCH)/isr.o
